name = "MyTestPackage"
uuid = "a275e943-03a4-428a-ab35-6bbcec06f221"
authors = ["blixi <eva.memmel@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
